# Generated by Django 3.0.3 on 2020-05-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200501_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='miktar'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='is_paid',
            field=models.BooleanField(verbose_name='Ödendi?'),
        ),
    ]
