# Generated by Django 3.0.3 on 2020-03-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200323_1243'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentstaff',
            options={'verbose_name': 'Çalışan', 'verbose_name_plural': 'Çalışanlar'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Öğrenci', 'verbose_name_plural': 'Öğrenciler'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Öğretmen', 'verbose_name_plural': 'Öğretmenler'},
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Department', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Department', verbose_name='Şube'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='known_langs',
            field=models.ManyToManyField(to='courses.Language', verbose_name='Bilinen Diller'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='start_work_time',
            field=models.DateTimeField(verbose_name='İşe başlama tarihi'),
        ),
    ]
