# Generated by Django 3.0.3 on 2020-03-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Teacher'),
        ),
        migrations.AddField(
            model_name='classroomunavailableslot',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Classroom'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Department'),
        ),
    ]
