# Generated by Django 3.0.3 on 2020-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200306_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Sınıf', 'verbose_name_plural': 'Sınıflar'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Şube', 'verbose_name_plural': 'Şubeler'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Dil', 'verbose_name_plural': 'Diller'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='extra_infos',
        ),
        migrations.AddField(
            model_name='department',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='department',
            name='private_transport_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Özel Ulaşım Bilgileri'),
        ),
        migrations.AddField(
            model_name='department',
            name='public_transport_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Toplu Ulaşım Bilgileri'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Şube'),
        ),
    ]
