# Generated by Django 3.0.3 on 2020-03-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200323_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_datetime',
        ),
    ]
