# Generated by Django 3.0.3 on 2020-03-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200323_1243'),
        ('courses', '0004_auto_20200323_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUnavailableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomUnavailableSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.Classroom')),
            ],
        ),
    ]
