# Generated by Django 3.0.3 on 2020-03-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherunavailableslot',
            old_name='classroom',
            new_name='teacher',
        ),
    ]
