# Generated by Django 3.0.3 on 2020-03-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200323_1520'),
        ('timeslots', '0002_auto_20200323_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomunavailableslot',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherunavailableslot',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson'),
            preserve_default=False,
        ),
    ]
